---
title: "CodeBook"
author: "Anjali"
date: "May 24, 2017"
output: html_document
---


## Introduction:

The purpose of this project is to demonstrate your ability to collect, work with, and clean a data set. The goal is to prepare tidy data that can be used for later analysis. You will be graded by your peers on a series of yes/no questions related to the project. You will be required to submit: 1) a tidy data set as described below, 2) a link to a Github repository with your script for performing the analysis, and 3) a code book that describes the variables, the data, and any transformations or work that you performed to clean up the data called CodeBook.md. You should also include a README.md in the repo with your scripts. This repo explains how all of the scripts work and how they are connected.

One of the most exciting areas in all of data science right now is wearable computing - see for example this article . Companies like Fitbit, Nike, and Jawbone Up are racing to develop the most advanced algorithms to attract new users. The data linked to from the course website represent data collected from the accelerometers from the Samsung Galaxy S smartphone. A full description is available at the site where the data was obtained:

http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones


## Data source:

Here are the data for the project:

https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip


## Files in the data package

- 'README.txt'

- 'features_info.txt': Shows information about the variables used on the feature vector.

- 'features.txt': List of all features.

- 'activity_labels.txt': Links the class labels with their activity name.

- 'train/X_train.txt': Training set.

- 'train/y_train.txt': Training labels.

- 'test/X_test.txt': Test set.

- 'test/y_test.txt': Test labels.

The following files are available for the train and test data. Their descriptions are equivalent. 

- 'train/subject_train.txt': Each row identifies the subject who performed the activity for each window sample. Its range is from 1 to 30. 

- 'train/Inertial Signals/total_acc_x_train.txt': The acceleration signal from the smartphone accelerometer X axis in standard gravity units 'g'. Every row shows a 128 element vector. The same description applies for the 'total_acc_x_train.txt' and 'total_acc_z_train.txt' files for the Y and Z axis. 

- 'train/Inertial Signals/body_acc_x_train.txt': The body acceleration signal obtained by subtracting the gravity from the total acceleration. 

- 'train/Inertial Signals/body_gyro_x_train.txt': The angular velocity vector measured by the gyroscope for each window sample. The units are radians/second. 

## Steps to clean up data and manipulate for each task for this project

#Q1: Merges the training and the test sets to create one data set.

**1-download "downloader" package to download file from web**

install.packages("downloader")

library("downloader")

**2-download files into the directory and unzip the file**

**3-Read and row bind Subject files test and train and name the variable appropriate name(sunjectid)**

**4-Read and row bind test and training data set and name the variable appropriate name(with the help of header file(features.txt)**

**5-Read and row bind the test and train labels and name the variable appropriately(activityid)**

**6-Column bind all the data frames formed above**


##Q2: Extracts only the measurements on the mean and standard deviation for each measurement.

You might need the "dplyr" package, so install it in your machine

install.packages("dplyr")

library("dplyr")

then run the select query with the matching clause on column names

**Example:**

mean_std_data_by_measure<-select(test_train,matches("subjectid|activity|mean|std"))


##Q3: Uses descriptive activity names to name the activities in the data set

Read the labels from "activity_labels.txt" file.

Merge the data frame formed in the previous step with the activity_label by a common field.

##Q4: Appropriately labels the data set with descriptive variable names.

Run the gsub() command on the dataset to substitute the accronym with the more meaninful name

**Example:**

colnames(test_train_with_actvity_labels)<-gsub("mean()","mean_value",colnames(test_train_with_actvity_labels))


##Q5: From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.

Removing the redundent field

Run the aggregate function and group the results by subjectid and activityname.

Write the results into a file.


